Repository g3offrey/javascript-test-runner, pull requests merged in 2018-07, with the labels that each got.

#11 Add environment variables settings for test runner and test debugging
  package.json
  src/commands/runTestCommand.ts
Labels: wip

#21 Troubleshooting guide for jest + typescript
  README.md
Labels: documentation

#23 Fix program for mocha runner
  src/commands/debugTestCommand.ts
  src/runners/MochaTestRunner.ts
  yarn.lock
Labels: bug
